### ISSUE TITLE
Support for `vim-lsp` plugin

### ISSUE THREAD

**Issue by maximyurevich** [girishji/vimcomplete#40]

**Comment by girishji** [comment]
Can you elaborate?

**Comment by maximyurevich** [comment]
I think this plugin should focus on supporting all lsp plugins that have the ability to use native lsp, including `vim-lsp`

**Comment by girishji** [comment]
Is it better than yegappan lsp? I have never used it since I prefer vim9 script over legacy script.

**Comment by girishji** [comment]
Actually I decide to write this after using yegappan completion engine! I actually wrote the vsnip adapter to yegappan lsp and made improvements to buffer search. But in the end I was not happy. So I created this plugin primarily for my own use.

It is possible that vim-lsp client is slower than yegappan lsp since legacy script is slow. It also takes some bandwidth to support another lsp client. They all have their quirks. If you are willing to write an adapter for vim-lsp I can help you.

**Comment by beavailable** [comment]
> Is it better than yegappan lsp? I have never used it since I prefer vim9 script over legacy script.

It is better at least for me, because it can work with `delimitMate`, yegappan lsp can't. 
I've opened an issue https://github.com/yegappan/lsp/issues/454 for this problem over a month ago, but haven't got any replies.

> It is possible that vim-lsp client is slower than yegappan lsp since legacy script is slow.

Actually it's not that slow, before I use your plugin, I've used `vim-lsp` for a few years in a low-power laptop and it works well.

I would very appreciate it if anyone could work on this.

**Comment by girishji** [comment]
It is not that difficult to add the support. It may even be trivial (for me, at least). The issue is maintaining, meaning, as issues pop up one has to dig into their legacy script codebase.

I saw the lexima you linked. There is a lot of code. I think some autocommand or mapping is conflicting with lsp. Have you tried `:h iabbrev`? You can do some amazing things with them. Also, does delimtMate work with this plugin (if you uninstall lsp)?

**Comment by beavailable** [comment]
> Have you tried `:h iabbrev`? You can do some amazing things with them.

I haven't tried `iabbrev`, I think it might not work well in some cases or not be as powerful as `delimitMate`.

> Also, does `delimtMate` work with this plugin (if you uninstall lsp)?

Both `delimitMate` and `lexima` can't work with `lsp`, and if I uninstall `lsp`, both works.

**Comment by girishji** [comment]
That's strange, autocompletion is disabled in lsp. Does it give errors?

**Comment by beavailable** [comment]
> That's strange, autocompletion is disabled in lsp.

Sorry, I don't know what this means. But no errors, I just can't get auto-closed parentheses.

**Comment by girishji** [comment]
LSP should not be interfering in the auto-completion mechanism actively.  But apparently it is.

**Comment by girishji** [comment]
[lexima](https://github.com/cohama/lexima.vim) works with Lsp if you set `showSignature: false`.
What happens (I guess) is that Lsp maps `(` as one of the trigger characters (https://github.com/yegappan/lsp/blob/f5adbd10cf2fc486c5101a61ed45489a0f6b8c40/autoload/lsp/signature.vim#L60), and lexima also maps the same character for auto-completion. Lsp overwrites lexima keymap.

**Comment by beavailable** [comment]
Thanks for help, I tried to set `showSignature: false`, it works for `delimitMate` too.
But `showSignature` is useful and I don't want to lose it.
After some research, I finally got them both work (also set `showSignature: false`):
```vim
au BufEnter * inoremap <silent> <buffer> ( (<Plug>delimitMate(<C-R>=g:LspShowSignature()<CR><BS>
```
It's not elegant, because I have to add `(` and then remove it (otherwise it won't work and I don't know why), but it's enough for me.

Thanks again, and I totally understand if you don't want to add support for `vim-lsp`.
